CREATE DATABASE wilde_bwd;

use wilde_bwd;

CREATE TABLE recipes (
	id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
	recipe VARCHAR(30) NOT NULL,
	recipe_description VARCHAR(100) NOT NULL,
	recipe_method VARCHAR(500) NOT NULL,
    protein VARCHAR(30),
    ingredients VARCHAR(500) NOT NULL
);
CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);